matrix:
  include:
    - language: r
      warnings_are_errors: true
      sudo: required
      cache: packages
      r_packages:
       - devtool
      r_github_packages:
       - r-lib/covr
      before_install:
       - cd r-package
       - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
       - sudo apt-get --yes --force-yes update -qq
       - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev
       - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'
      #install:
      # - travis_wait mvn install
      script:
        - R CMD build .
        - travis_wait 120 R CMD check *tar.gz
      after_success:
       - travis_wait 120 Rscript -e 'covr::codecov()'

    - language: python
      python:
        - "3.6"      # current default Python on Travis CI
        - "3.7"
      before_install:
        - cd python-package
        - pip install -U pip
        - pip install -U pytest
        - pip install codecov
      # command to install dependencies
      install:
        - pip install -r requirements.txt
      # command to run tests
      script:
        - pytest
      after_success:
        - codecov # submit coverage
