language: r

warnings_are_errors: true

sudo: required

cache: packages

r_packages:
 - devtools

r_github_packages:
  - r-lib/covr

#r_binary_packages:
# - libgit2

before_install:
 - cd r-package
 - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
 - sudo apt-get --yes --force-yes update -qq
 - sudo apt-get install --yes udunits-bin libproj-dev libgeos-dev libgdal-dev libgdal1-dev libudunits2-dev
 - R -e 'install.packages("rgdal", repos="http://R-Forge.R-project.org")'

install: travis_wait mvn install

after_success:
 - travis_wait Rscript -e 'covr::codecov()'
